const storageKey = 'diari-kombutxa-v3';
const draftKey = 'diari-kombutxa-draft-v1';
const q = id => document.querySelector(`#${id}`);
const today = () => new Date().toISOString().slice(0, 10);
const localDate = value => new Date(`${value}T12:00:00`);
const isoDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const amount = value => Number(value).toLocaleString('ca-ES', { maximumFractionDigits: 1 });
let editingF1 = null, editingF2 = null, pendingPhotos = [], pendingF1Photos = [], calendarCursor = new Date(new Date().getFullYear(), new Date().getMonth(), 1), selectedRecords = new Set(), registryListMode = localStorage.getItem('diari-kombutxa-registry-view') === 'list';
const sharedImport = {
  f1: [{ id: 'shared-f1-2026-07-21', date: '2026-07-21', liters: '3', temperature: '', ph: '', days: '', notes: 'Base registrada al xat: 2.400 ml de te + 600 ml de base/iniciador.' }],
  f2: [
    { id: 'shared-f2-strawberry', f1Id: 'shared-f1-2026-07-21', name: 'Maduixa', date: '2026-07-30', liters: '0.2', fruit: 'maduixa', days: '', ingredients: '20 g de maduixa (quantitat indicada al xat).', notes: 'Volum inferit a partir de la proporció de 100 g/L; revisa’l si cal.', photos: [] },
    { id: 'shared-f2-apple', f1Id: 'shared-f1-2026-07-21', name: 'Poma', date: '2026-07-30', liters: '0.2', fruit: 'poma', days: '', ingredients: '20 g de poma (quantitat indicada al xat).', notes: 'Volum inferit a partir de la proporció de 100 g/L; revisa’l si cal.', photos: [] },
    { id: 'shared-f2-berries', f1Id: 'shared-f1-2026-07-21', name: 'Maduixa i fruits vermells · segona tanda', date: '2026-07-30', liters: '0.9', fruit: 'maduixa i fruits vermells', days: '', ingredients: '100 g de fruita total: 50 g de puré de fruits vermells i 50 g de maduixa congelada.', notes: 'Base indicada: 900 ml de F1. La fruita real va ser 100 g en total.', photos: [] }
  ]
};

function getData() {
  const stored = JSON.parse(localStorage.getItem(storageKey) || 'null');
  if (stored) {
    if (!stored.sharedImport2026) { stored.f1 = [...sharedImport.f1.filter(seed => !stored.f1.some(item => item.id === seed.id)), ...stored.f1]; stored.f2 = [...sharedImport.f2.filter(seed => !stored.f2.some(item => item.id === seed.id)), ...stored.f2]; stored.sharedImport2026 = true; localStorage.setItem(storageKey, JSON.stringify(stored)); }
    return stored;
  }
  const old = JSON.parse(localStorage.getItem('diari-kombutxa-v2') || localStorage.getItem('diari-kombutxa-v1') || '[]');
  const imported = { f1: sharedImport.f1, f2: [...sharedImport.f2, ...old.map(item => ({ id: item.id, name: item.name, date: item.startDate, liters: item.f2Liters || item.f1Liters, fruit: item.f2Fruit || item.f2Flavors, days: item.f2Days, ingredients: item.ingredients, notes: item.notes, photos: item.photos || [], f1Id: '' }))], sharedImport2026: true };
  localStorage.setItem(storageKey, JSON.stringify(imported)); return imported;
}
const saveData = data => { data.updatedAt = Date.now(); localStorage.setItem(storageKey, JSON.stringify(data)); window.kombutxaCloud?.save(data); };
const f1Recipe = liters => liters ? `Recepta base per ${amount(liters)} L\n• Aigua: ${amount(liters)} L\n• Te: ${amount(liters * 5)} g\n• Sucre: ${amount(liters * 70)} g\n• Líquid iniciador: ${amount(liters * 100)} ml\n• SCOBY: 1 cultiu saludable` : '';
const ingredientRates = { 'maduixa': 100, 'fruits vermells': 100, 'poma': 100, 'taronja': 100, 'gingebre': 10, 'llimona': 30, 'menta': 5 };
const f2Recipe = (liters, components) => liters && components.length ? `F2 per ${amount(liters)} L\n${components.map(component => `• ${component.name}: ${amount(liters * component.rate)} g`).join('\n')}` : '';
function formComponents() { return [...q('f2-components').querySelectorAll('.component-row')].map(row => ({ name: row.querySelector('.component-name').value.trim(), rate: Number(row.querySelector('.component-rate').value) })).filter(component => component.name && component.rate > 0); }
function renderComponents(components) { const container = q('f2-components'); container.innerHTML = ''; components.forEach(component => { const row = document.createElement('div'); row.className = 'component-row'; row.innerHTML = `<label>Ingredient<input class="component-name" list="ingredient-options" value="${component.name}" required /></label><label>Dosi g/L<input class="component-rate" type="number" min="0.1" step="0.1" value="${component.rate}" required /></label><button type="button" class="delete-button" aria-label="Elimina ingredient">×</button>`; const name = row.querySelector('.component-name'), rate = row.querySelector('.component-rate'); name.onchange = () => { const suggestion = ingredientRates[name.value.trim().toLowerCase()]; if (suggestion) rate.value = suggestion; updateRecipes(); }; rate.oninput = updateRecipes; row.querySelector('.delete-button').onclick = () => { row.remove(); updateRecipes(); }; container.append(row); }); updateRecipes(); }
const fileName = text => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'prova-kombutxa';
function saveDraft() { localStorage.setItem(draftKey, JSON.stringify({ f1: ['f1-date','f1-liters','f1-temperature','f1-ph','f1-days','f1-notes'].reduce((out,id) => ({ ...out, [id]: q(id).value }), {}), f2: ['f2-f1-id','f2-name','f2-date','f2-liters','f2-days','f2-ingredients','f2-notes'].reduce((out,id) => ({ ...out, [id]: q(id).value }), {}), components: formComponents() })); }
function restoreDraft() { const draft = JSON.parse(localStorage.getItem(draftKey) || 'null'); if (!draft) return; Object.entries(draft.f1 || {}).forEach(([id,value]) => q(id).value = value || ''); Object.entries(draft.f2 || {}).forEach(([id,value]) => q(id).value = value || ''); renderComponents(draft.components?.length ? draft.components : [{ name: 'Maduixa', rate: 100 }]); updateRecipes(); }

function resetF1() { editingF1 = null; pendingF1Photos = []; q('f1-form').reset(); q('f1-date').value = today(); q('f1-title').textContent = 'F1 · Producció'; q('save-f1').textContent = 'Desa la producció'; showF1Photos(); updateRecipes(); }
function resetF2() { editingF2 = null; pendingPhotos = []; q('f2-form').reset(); q('f2-date').value = today(); q('f2-title').textContent = 'F2 · Nova prova'; q('save-f2').textContent = 'Desa la prova'; showPhotos(); renderComponents([{ name: 'Maduixa', rate: 100 }]); }
function updateRecipes() { q('f1-recipe').textContent = f1Recipe(Number(q('f1-liters').value)) || 'Introdueix els litres per calcular la recepta.'; q('f2-recipe').textContent = f2Recipe(Number(q('f2-liters').value), formComponents()) || 'Indica quantitat i un o més ingredients per calcular la F2.'; }
function showPhotos() { const preview = q('f2-photo-preview'); preview.innerHTML = ''; pendingPhotos.forEach((source, index) => { const wrap = document.createElement('div'), image = new Image(), button = document.createElement('button'); image.src = source; image.alt = 'Foto de la prova'; button.type = 'button'; button.className = 'delete-button'; button.textContent = '×'; button.onclick = () => { pendingPhotos.splice(index, 1); showPhotos(); }; wrap.append(image, button); preview.append(wrap); }); }
function showF1Photos() { const preview = q('f1-photo-preview'); preview.innerHTML = ''; pendingF1Photos.forEach((source, index) => { const wrap = document.createElement('div'), image = new Image(), button = document.createElement('button'); image.src = source; image.alt = 'Foto de la producció'; button.type = 'button'; button.className = 'delete-button'; button.textContent = '×'; button.onclick = () => { pendingF1Photos.splice(index, 1); showF1Photos(); }; wrap.append(image, button); preview.append(wrap); }); }
function baseName(id, data) { const base = data.f1.find(item => item.id === id); return base ? `Base F1: ${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(base.date))} · ${base.liters} L` : 'Base F1: sense vincular'; }

function renderSelectors(data) { const select = q('f2-f1-id'), selected = select.value; select.innerHTML = '<option value="">Sense vincular</option>'; data.f1.forEach(item => { const option = document.createElement('option'); option.value = item.id; option.textContent = `${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.date))} · ${item.liters} L`; select.append(option); }); select.value = selected; }
function render() {
  const data = getData(); renderSelectors(data); renderF1(data); renderF2(data); renderCalendar(data); updateSelectionHelp(); applyRegistryView();
}
function enableRegistryCardExpansion(card) {
  card.addEventListener('click', event => {
    if (!registryListMode || event.target.closest('button, input, label, a')) return;
    const isExpanded = card.classList.toggle('is-expanded');
    card.setAttribute('aria-expanded', String(isExpanded));
  });
}

function renderF1(data) {
  const ordered = [...data.f1].sort((a,b) => b.date.localeCompare(a.date)); q('f1-count').textContent = ordered.length ? `${ordered.length} producció${ordered.length === 1 ? '' : 'ns'}` : ''; q('f1-empty').hidden = ordered.length > 0; q('f1-list').innerHTML = '';
  ordered.forEach(item => { const node = q('f1-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f1:${item.id}`, check = node.querySelector('.record-check'); card.id = `f1-${item.id}`; enableRegistryCardExpansion(card); check.checked = selectedRecords.has(key); check.onchange = () => { check.checked ? selectedRecords.add(key) : selectedRecords.delete(key); updateSelectionHelp(); }; node.querySelector('.card-date').textContent = new Intl.DateTimeFormat('ca-ES', { dateStyle: 'long' }).format(localDate(item.date)); node.querySelector('.values').innerHTML = [['Quantitat', `${item.liters} L`], ['Temperatura', item.temperature && `${item.temperature} °C`], ['pH', item.ph], ['Durada', item.days && `${item.days} dies`]].filter(([,v]) => v).map(([k,v]) => `<div><dt>${k}</dt><dd> ${v}</dd></div>`).join(''); node.querySelector('.recipe').textContent = f1Recipe(Number(item.liters)); node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : ''; (item.photos || []).forEach(photo => { const image = new Image(); image.src = photo; image.alt = 'Foto de la producció F1'; node.querySelector('.gallery').append(image); }); node.querySelector('.edit-button').onclick = () => editF1(item); node.querySelector('.delete-button').onclick = () => remove('f1', item.id); q('f1-list').append(node); });
}
function renderF2(data) {
  const ordered = [...data.f2].sort((a,b) => b.date.localeCompare(a.date)); q('f2-count').textContent = ordered.length ? `${ordered.length} prova${ordered.length === 1 ? '' : 'es'}` : ''; q('f2-empty').hidden = ordered.length > 0; q('f2-list').innerHTML = '';
  ordered.forEach(item => { const components = item.components || [{ name: item.fruit || 'Fruita', rate: 100 }], node = q('f2-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f2:${item.id}`, check = node.querySelector('.record-check'); card.id = `f2-${item.id}`; enableRegistryCardExpansion(card); check.checked = selectedRecords.has(key); check.onchange = () => { check.checked ? selectedRecords.add(key) : selectedRecords.delete(key); updateSelectionHelp(); }; node.querySelector('h3').textContent = item.name; node.querySelector('.card-date').textContent = `Embotellada: ${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'long' }).format(localDate(item.date))}`; node.querySelector('.base').textContent = baseName(item.f1Id, data); node.querySelector('.values').innerHTML = [['Quantitat', `${item.liters} L`], ['F2', item.days && `${item.days} dies`]].filter(([,v]) => v).map(([k,v]) => `<div><dt>${k}</dt><dd> ${v}</dd></div>`).join(''); node.querySelector('.recipe').textContent = f2Recipe(Number(item.liters), components); node.querySelector('.ingredients').textContent = item.ingredients ? `Notes d’ingredients: ${item.ingredients}` : ''; node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : ''; (item.photos || []).forEach(photo => { const image = new Image(); image.src = photo; image.alt = `Foto de ${item.name}`; node.querySelector('.gallery').append(image); }); node.querySelector('.edit-button').onclick = () => editF2(item); node.querySelector('.delete-button').onclick = () => remove('f2', item.id); node.querySelector('.pdf-button').onclick = () => pdf(item, data); node.querySelector('.word-button').onclick = () => word(item, data); q('f2-list').append(node); });
}
function editF1(item) { editingF1 = item.id; [['f1-date',item.date],['f1-liters',item.liters],['f1-temperature',item.temperature],['f1-ph',item.ph],['f1-days',item.days],['f1-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingF1Photos = [...(item.photos || [])]; q('f1-title').textContent = 'Edita la producció F1'; q('save-f1').textContent = 'Desa els canvis'; showF1Photos(); updateRecipes(); setView('production'); q('f1-form').scrollIntoView({ behavior: 'smooth' }); }
function editF2(item) { editingF2 = item.id; [['f2-f1-id',item.f1Id],['f2-name',item.name],['f2-date',item.date],['f2-liters',item.liters],['f2-days',item.days],['f2-ingredients',item.ingredients],['f2-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingPhotos = [...(item.photos || [])]; q('f2-title').textContent = 'Edita la prova F2'; q('save-f2').textContent = 'Desa els canvis'; showPhotos(); renderComponents(item.components || [{ name: item.fruit || 'Maduixa', rate: 100 }]); setView('production'); q('f2-form').scrollIntoView({ behavior: 'smooth' }); }
function remove(type, id) { if (!confirm('Vols eliminar aquest registre?')) return; const data = getData(); data[type] = data[type].filter(item => item.id !== id); selectedRecords.delete(`${type}:${id}`); saveData(data); render(); }
function report(item, data) { const components = item.components || [{ name: item.fruit || 'Fruita', rate: 100 }]; return [['Base F1',baseName(item.f1Id,data)],['Data d’embotellat',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat F2',`${item.liters} L`],['Recepta F2',f2Recipe(Number(item.liters),components)],['Durada de F2',item.days && `${item.days} dies`],['Notes d’ingredients',item.ingredients],['Notes',item.notes]].filter(([,v])=>v); }
function pdf(item,data) { const { jsPDF } = window.jspdf, doc = new jsPDF({ unit:'mm', format:'a4' }); let y=20; doc.setFont('helvetica','bold'); doc.setFontSize(20); doc.text('Informe de prova F2',18,y); y+=11; doc.setFontSize(15); doc.text(item.name,18,y); y+=10; doc.setFont('helvetica','normal'); doc.setFontSize(10); report(item,data).forEach(([label,value])=>{ const lines=doc.splitTextToSize(`${label}: ${value}`,174); if(y+lines.length*5>276){doc.addPage();y=20;} doc.text(lines,18,y); y+=lines.length*5+3; }); (item.photos||[]).forEach((photo,index)=>{if(y>210){doc.addPage();y=20;} doc.text(`Foto ${index+1}`,18,y);y+=4;doc.addImage(photo,photo.startsWith('data:image/png')?'PNG':'JPEG',18,y,55,55);y+=63;}); doc.save(`${fileName(item.name)}.pdf`); }
async function word(item,data) { if(!window.docx){alert('No s’ha pogut carregar l’exportació Word.');return;} const {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun}=window.docx; const children=[new Paragraph({text:'Informe de prova F2',heading:HeadingLevel.TITLE}),new Paragraph({text:item.name,heading:HeadingLevel.HEADING_1})]; report(item,data).forEach(([label,value])=>children.push(new Paragraph({children:[new TextRun({text:`${label}: `,bold:true}),new TextRun(String(value))]}))); for(const [index,photo] of (item.photos||[]).entries()){const bytes=new Uint8Array(await(await fetch(photo)).arrayBuffer());children.push(new Paragraph({text:`Foto ${index+1}`,heading:HeadingLevel.HEADING_2}),new Paragraph({children:[new ImageRun({data:bytes,transformation:{width:220,height:165}})]}));} const blob=await Packer.toBlob(new Document({sections:[{children}]}));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${fileName(item.name)}.docx`;a.click();URL.revokeObjectURL(a.href); }
function selectedItems(data) { return [...selectedRecords].map(key => { const [type, id] = key.split(':'); const item = data[type]?.find(record => record.id === id); return item ? { type, item } : null; }).filter(Boolean); }
function f1Report(item) { return [['Data d’inici',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat F1',`${item.liters} L`],['Recepta F1',f1Recipe(Number(item.liters))],['Temperatura',item.temperature && `${item.temperature} °C`],['pH',item.ph],['Durada',item.days && `${item.days} dies`],['Notes',item.notes]].filter(([,value]) => value); }
function recordReport(entry, data) { return entry.type === 'f1' ? { title: `Producció F1 · ${entry.item.liters} L`, rows: f1Report(entry.item) } : { title: `Prova F2 · ${entry.item.name}`, rows: report(entry.item, data) }; }
function updateSelectionHelp() { const selected = selectedRecords.size; q('selection-help').textContent = selected ? `${selected} registre${selected === 1 ? '' : 's'} seleccionat${selected === 1 ? '' : 's'}.` : 'No hi ha cap registre seleccionat.'; }
function applyRegistryView() { q('f1-list').classList.toggle('is-list',registryListMode); q('f2-list').classList.toggle('is-list',registryListMode); q('toggle-record-list').textContent = registryListMode ? 'Veure en targetes' : 'Veure en format llista'; }
function exportSelectedPdf() { const data = getData(), entries = selectedItems(data); if (!entries.length) { alert('Selecciona almenys un registre.'); return; } const { jsPDF } = window.jspdf, doc = new jsPDF({ unit:'mm', format:'a4' }); entries.forEach((entry,index) => { if (index) doc.addPage(); let y = 20; const record = recordReport(entry,data); doc.setFont('helvetica','bold'); doc.setFontSize(18); doc.text('Registre de kombutxa',18,y); y += 10; doc.setFontSize(13); doc.text(record.title,18,y); y += 9; doc.setFont('helvetica','normal'); doc.setFontSize(10); record.rows.forEach(([label,value]) => { const lines = doc.splitTextToSize(`${label}: ${value}`,174); if (y + lines.length * 5 > 276) { doc.addPage(); y = 20; } doc.text(lines,18,y); y += lines.length * 5 + 3; }); }); doc.save('registre-kombutxa-seleccionat.pdf'); }
async function exportSelectedWord() { const data = getData(), entries = selectedItems(data); if (!entries.length) { alert('Selecciona almenys un registre.'); return; } if (!window.docx) { alert('No s’ha pogut carregar l’exportació Word.'); return; } const {Document,Packer,Paragraph,TextRun,HeadingLevel} = window.docx, children = [new Paragraph({text:'Registre de kombutxa',heading:HeadingLevel.TITLE})]; entries.forEach(entry => { const record = recordReport(entry,data); children.push(new Paragraph({text:record.title,heading:HeadingLevel.HEADING_1})); record.rows.forEach(([label,value]) => children.push(new Paragraph({children:[new TextRun({text:`${label}: `,bold:true}),new TextRun(String(value))]}))); }); const blob = await Packer.toBlob(new Document({sections:[{children}]})); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'registre-kombutxa-seleccionat.docx'; link.click(); URL.revokeObjectURL(link.href); }
const escapeHtml = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function compareSelected() { const data = getData(), entries = selectedItems(data).filter(entry => entry.type === 'f2'); if (entries.length < 2) { alert('Selecciona almenys dues proves F2 per comparar-les.'); return; } const fields = [['Data',entry => new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(entry.item.date))],['Quantitat',entry => `${entry.item.liters} L`],['Dies F2',entry => entry.item.days ? `${entry.item.days} dies` : '—'],['Recepta',entry => f2Recipe(Number(entry.item.liters),entry.item.components || [{name:entry.item.fruit || 'Fruita',rate:100}])],['Notes ingredients',entry => entry.item.ingredients || '—'],['Notes de prova',entry => entry.item.notes || '—']]; q('comparison-table').innerHTML = `<div class="comparison-table-wrap"><table class="comparison-table"><thead><tr><th>Camp</th>${entries.map(entry => `<th>${escapeHtml(entry.item.name)}</th>`).join('')}</tr></thead><tbody>${fields.map(([label,getValue]) => `<tr><th>${label}</th>${entries.map(entry => `<td>${escapeHtml(getValue(entry))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; q('comparison-panel').hidden = false; q('comparison-panel').scrollIntoView({behavior:'smooth'}); }
function setView(view) { document.querySelectorAll('[data-view]').forEach(panel => panel.hidden = panel.dataset.view !== view || (panel.id === 'comparison-panel' && !q('comparison-table').innerHTML)); document.querySelectorAll('[data-view-button]').forEach(button => { const active = button.dataset.viewButton === view; button.classList.toggle('is-active',active); button.setAttribute('aria-selected',String(active)); }); }
function renderCalendar(data) { const label=new Intl.DateTimeFormat('ca-ES',{month:'long',year:'numeric'}).format(calendarCursor);q('calendar-month').textContent=label.charAt(0).toUpperCase()+label.slice(1);const days=q('calendar-days');days.innerHTML='';const start=new Date(calendarCursor),first=new Date(start);first.setDate(1-((start.getDay()+6)%7));for(let i=0;i<42;i++){const date=new Date(first);date.setDate(first.getDate()+i);const key=isoDate(date),cell=document.createElement('div');cell.className=`calendar-day${date.getMonth()!==calendarCursor.getMonth()?' is-outside':''}`;cell.innerHTML=`<span class="day-number">${date.getDate()}</span>`;[...data.f1.map(x=>({date:x.date,label:`F1 · ${x.liters} L`,id:`f1-${x.id}`})),...data.f2.map(x=>({date:x.date,label:`F2 · ${x.name}`,id:`f2-${x.id}`}))].filter(x=>x.date===key).forEach(event=>{const button=document.createElement('button');button.className='calendar-event';button.textContent=event.label;button.onclick=()=>q(event.id)?.scrollIntoView({behavior:'smooth'});cell.append(button);});days.append(cell);} }
q('f1-form').onsubmit=event=>{event.preventDefault();const data=getData(),item={id:editingF1||crypto.randomUUID(),date:q('f1-date').value,liters:q('f1-liters').value,temperature:q('f1-temperature').value,ph:q('f1-ph').value,days:q('f1-days').value,notes:q('f1-notes').value.trim(),photos:pendingF1Photos};data.f1=editingF1?data.f1.map(x=>x.id===editingF1?item:x):[item,...data.f1];saveData(data);localStorage.removeItem(draftKey);resetF1();render();};
q('f2-form').onsubmit=event=>{event.preventDefault();const data=getData(),item={id:editingF2||crypto.randomUUID(),f1Id:q('f2-f1-id').value,name:q('f2-name').value.trim(),date:q('f2-date').value,liters:q('f2-liters').value,components:formComponents(),days:q('f2-days').value,ingredients:q('f2-ingredients').value.trim(),notes:q('f2-notes').value.trim(),photos:pendingPhotos};data.f2=editingF2?data.f2.map(x=>x.id===editingF2?item:x):[item,...data.f2];saveData(data);localStorage.removeItem(draftKey);resetF2();render();};
const compactPhoto = file => new Promise(resolve => { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 1280 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', 0.8)); }; image.onerror = () => resolve(reader.result); image.src = reader.result; }; reader.readAsDataURL(file); });
q('f2-photos').onchange=async()=>{const photos=await Promise.all([...q('f2-photos').files].map(compactPhoto));pendingPhotos.push(...photos);q('f2-photos').value='';showPhotos();};
q('f1-photos').onchange=async()=>{const photos=await Promise.all([...q('f1-photos').files].map(compactPhoto));pendingF1Photos.push(...photos);q('f1-photos').value='';showF1Photos();};
q('clear-f1').onclick=()=>{localStorage.removeItem(draftKey);resetF1();};q('clear-f2').onclick=()=>{localStorage.removeItem(draftKey);resetF2();};q('add-ingredient').onclick=()=>renderComponents([...formComponents(),{ name: 'Gingebre', rate: 10 }]);['f1-liters','f2-liters'].forEach(id=>q(id).oninput=updateRecipes);q('previous-month').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar(getData());};q('next-month').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar(getData());};q('toggle-record-list').onclick=()=>{registryListMode=!registryListMode;localStorage.setItem('diari-kombutxa-registry-view',registryListMode?'list':'cards');applyRegistryView();};q('select-all-records').onclick=()=>{const data=getData();selectedRecords=new Set([...data.f1.map(item=>`f1:${item.id}`),...data.f2.map(item=>`f2:${item.id}`)]);render();};q('clear-record-selection').onclick=()=>{selectedRecords.clear();q('comparison-table').innerHTML='';q('comparison-panel').hidden=true;render();};q('export-selected-pdf').onclick=exportSelectedPdf;q('export-selected-word').onclick=exportSelectedWord;q('compare-selected').onclick=compareSelected;q('close-comparison').onclick=()=>{q('comparison-table').innerHTML='';q('comparison-panel').hidden=true;};document.querySelectorAll('[data-view-button]').forEach(button=>button.onclick=()=>setView(button.dataset.viewButton));document.addEventListener('input', event => { if (event.target.closest('#f1-form') || event.target.closest('#f2-form')) saveDraft(); });window.addEventListener('kombutxa-cloud-data', () => { if (!editingF1 && !editingF2) render(); });resetF1();resetF2();render();restoreDraft();setView('production');
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');

