const storageKey = 'diari-kombutxa-v3';
const draftKey = 'diari-kombutxa-draft-v1';
const q = id => document.querySelector(`#${id}`);
const today = () => new Date().toISOString().slice(0, 10);
const localDate = value => new Date(`${value}T12:00:00`);
const isoDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const amount = value => Number(value).toLocaleString('ca-ES', { maximumFractionDigits: 1 });
let editingF1 = null, editingF2 = null, editingF3 = null, pendingPhotos = [], pendingF1Photos = [], pendingF3Photos = [], calendarCursor = new Date(new Date().getFullYear(), new Date().getMonth(), 1), selectedRecords = new Set(), registryListMode = localStorage.getItem('diari-kombutxa-registry-view') === 'list';
const sharedImport = {
  f1: [{ id: 'shared-f1-2026-07-21', date: '2026-07-21', liters: '3', temperature: '', ph: '', days: '', notes: 'Base registrada al xat: 2.400 ml de te + 600 ml de base/iniciador.' }],
  f2: [
    { id: 'shared-f2-strawberry', f1Id: 'shared-f1-2026-07-21', name: 'Maduixa', date: '2026-07-30', liters: '0.2', fruit: 'maduixa', days: '', ingredients: '20 g de maduixa (quantitat indicada al xat).', notes: 'Volum inferit a partir de la proporció de 100 g/L; revisa’l si cal.', photos: [] },
    { id: 'shared-f2-apple', f1Id: 'shared-f1-2026-07-21', name: 'Poma', date: '2026-07-30', liters: '0.2', fruit: 'poma', days: '', ingredients: '20 g de poma (quantitat indicada al xat).', notes: 'Volum inferit a partir de la proporció de 100 g/L; revisa’l si cal.', photos: [] },
    { id: 'shared-f2-berries', f1Id: 'shared-f1-2026-07-21', name: 'Maduixa i fruits vermells · segona tanda', date: '2026-07-30', liters: '0.9', fruit: 'maduixa i fruits vermells', days: '', ingredients: '100 g de fruita total: 50 g de puré de fruits vermells i 50 g de maduixa congelada.', notes: 'Base indicada: 900 ml de F1. La fruita real va ser 100 g en total.', photos: [] }
  ], f3: []
};

function getData() {
  const stored = JSON.parse(localStorage.getItem(storageKey) || 'null');
  if (stored) {
    stored.f3 ||= []; if (!stored.sharedImport2026) { stored.f1 = [...sharedImport.f1.filter(seed => !stored.f1.some(item => item.id === seed.id)), ...stored.f1]; stored.f2 = [...sharedImport.f2.filter(seed => !stored.f2.some(item => item.id === seed.id)), ...stored.f2]; stored.sharedImport2026 = true; localStorage.setItem(storageKey, JSON.stringify(stored)); }
    return stored;
  }
  const old = JSON.parse(localStorage.getItem('diari-kombutxa-v2') || localStorage.getItem('diari-kombutxa-v1') || '[]');
  const imported = { f1: sharedImport.f1, f2: [...sharedImport.f2, ...old.map(item => ({ id: item.id, name: item.name, date: item.startDate, liters: item.f2Liters || item.f1Liters, fruit: item.f2Fruit || item.f2Flavors, days: item.f2Days, ingredients: item.ingredients, notes: item.notes, photos: item.photos || [], f1Id: '' }))], f3: [], sharedImport2026: true };
  localStorage.setItem(storageKey, JSON.stringify(imported)); return imported;
}
const saveData = data => { data.updatedAt = Date.now(); localStorage.setItem(storageKey, JSON.stringify(data)); window.kombutxaCloud?.save(data); };
const f1Recipe = liters => liters ? `Recepta base per ${amount(liters)} L\n• Aigua: ${amount(liters)} L\n• Te: ${amount(liters * 5)} g\n• Sucre: ${amount(liters * 70)} g\n• Líquid iniciador: ${amount(liters * 100)} ml\n• SCOBY: 1 cultiu saludable` : '';
const ingredientRates = { 'maduixa': 100, 'fruits vermells': 100, 'poma': 100, 'taronja': 100, 'gingebre': 10, 'llimona': 30, 'menta': 5 };
const f2Recipe = (liters, components) => liters && components.length ? `F2 per ${amount(liters)} L\n${components.map(component => `• ${component.name}: ${amount(liters * component.rate)} g`).join('\n')}` : '';
function formComponents() { return [...q('f2-components').querySelectorAll('.component-row')].map(row => ({ name: row.querySelector('.component-name').value.trim(), rate: Number(row.querySelector('.component-rate').value) })).filter(component => component.name && component.rate > 0); }
function renderComponents(components) { const container = q('f2-components'); container.innerHTML = ''; components.forEach(component => { const row = document.createElement('div'); row.className = 'component-row'; row.innerHTML = `<label>Ingredient<input class="component-name" list="ingredient-options" value="${component.name}" required /></label><label>Dosi g/L<input class="component-rate" type="number" min="0.1" step="0.1" value="${component.rate}" required /></label><button type="button" class="delete-button" aria-label="Elimina ingredient">×</button>`; const name = row.querySelector('.component-name'), rate = row.querySelector('.component-rate'); name.onchange = () => { const suggestion = ingredientRates[name.value.trim().toLowerCase()]; if (suggestion) rate.value = suggestion; updateRecipes(); }; rate.oninput = updateRecipes; row.querySelector('.delete-button').onclick = () => { row.remove(); updateRecipes(); }; container.append(row); }); updateRecipes(); }
const fileName = text => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'prova-kombutxa';
function saveDraft() { localStorage.setItem(draftKey, JSON.stringify({ f1: ['f1-date','f1-liters','f1-temperature','f1-ph','f1-days','f1-notes'].reduce((out,id) => ({ ...out, [id]: q(id).value }), {}), f2: ['f2-f1-id','f2-name','f2-date','f2-liters','f2-days','f2-ingredients','f2-notes'].reduce((out,id) => ({ ...out, [id]: q(id).value }), {}), f3: ['f3-f2-id','f3-date','f3-liters','f3-bottles','f3-lot','f3-storage-temperature','f3-status','f3-best-before','f3-consumed-date','f3-notes'].reduce((out,id) => ({ ...out, [id]: q(id).value }), {}), components: formComponents() })); }
function restoreDraft() { const draft = JSON.parse(localStorage.getItem(draftKey) || 'null'); if (!draft) return; Object.entries(draft.f1 || {}).forEach(([id,value]) => q(id).value = value || ''); Object.entries(draft.f2 || {}).forEach(([id,value]) => q(id).value = value || ''); Object.entries(draft.f3 || {}).forEach(([id,value]) => q(id).value = value || ''); renderComponents(draft.components?.length ? draft.components : [{ name: 'Maduixa', rate: 100 }]); updateRecipes(); }

function resetF1() { editingF1 = null; pendingF1Photos = []; q('f1-form').reset(); q('f1-date').value = today(); q('f1-title').textContent = 'F1 · Producció'; q('save-f1').textContent = 'Desa la producció'; showF1Photos(); updateRecipes(); }
function resetF2() { editingF2 = null; pendingPhotos = []; q('f2-form').reset(); q('f2-date').value = today(); q('f2-title').textContent = 'F2 · Nova prova'; q('save-f2').textContent = 'Desa la prova'; showPhotos(); renderComponents([{ name: 'Maduixa', rate: 100 }]); }
function resetF3() { editingF3 = null; pendingF3Photos = []; q('f3-form').reset(); q('f3-date').value = today(); q('f3-status').value = 'stock'; q('f3-title').textContent = 'F3 · Conservació i consum'; q('save-f3').textContent = 'Desa la conservació'; showF3Photos(); }
function updateRecipes() { q('f1-recipe').textContent = f1Recipe(Number(q('f1-liters').value)) || 'Introdueix els litres per calcular la recepta.'; q('f2-recipe').textContent = f2Recipe(Number(q('f2-liters').value), formComponents()) || 'Indica quantitat i un o més ingredients per calcular la F2.'; }
function showPhotos() { const preview = q('f2-photo-preview'); preview.innerHTML = ''; pendingPhotos.forEach((source, index) => { const wrap = document.createElement('div'), image = new Image(), button = document.createElement('button'); image.src = source; image.alt = 'Foto de la prova'; button.type = 'button'; button.className = 'delete-button'; button.textContent = '×'; button.onclick = () => { pendingPhotos.splice(index, 1); showPhotos(); }; wrap.append(image, button); preview.append(wrap); }); }
function showF1Photos() { const preview = q('f1-photo-preview'); preview.innerHTML = ''; pendingF1Photos.forEach((source, index) => { const wrap = document.createElement('div'), image = new Image(), button = document.createElement('button'); image.src = source; image.alt = 'Foto de la producció'; button.type = 'button'; button.className = 'delete-button'; button.textContent = '×'; button.onclick = () => { pendingF1Photos.splice(index, 1); showF1Photos(); }; wrap.append(image, button); preview.append(wrap); }); }
function showF3Photos() { const preview = q('f3-photo-preview'); preview.innerHTML = ''; pendingF3Photos.forEach((source, index) => { const wrap = document.createElement('div'), image = new Image(), button = document.createElement('button'); image.src = source; image.alt = 'Foto de la conservació'; button.type = 'button'; button.className = 'delete-button'; button.textContent = '×'; button.onclick = () => { pendingF3Photos.splice(index, 1); showF3Photos(); }; wrap.append(image, button); preview.append(wrap); }); }
function baseName(id, data) { const base = data.f1.find(item => item.id === id); return base ? `Base F1: ${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(base.date))} · ${base.liters} L` : 'Base F1: sense vincular'; }

function renderSelectors(data) { const select = q('f2-f1-id'), selected = select.value; select.innerHTML = '<option value="">Sense vincular</option>'; data.f1.forEach(item => { const option = document.createElement('option'); option.value = item.id; option.textContent = `${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.date))} · ${item.liters} L`; select.append(option); }); select.value = selected; const f3Select = q('f3-f2-id'), f3Selected = f3Select.value, isAlreadyStored = f2 => data.f3.some(conservation => conservation.f2Id === f2.id && conservation.id !== editingF3); f3Select.innerHTML = '<option value="">Selecciona una F2</option>'; [...data.f2].filter(item => !isAlreadyStored(item)).sort((a,b) => b.date.localeCompare(a.date)).forEach(item => { const option = document.createElement('option'); option.value = item.id; option.textContent = `${item.name} · ${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.date))} · ${item.liters} L`; f3Select.append(option); }); f3Select.value = f3Selected; }
function render() {
  const data = getData(); renderSelectors(data); renderF1(data); renderF2(data); renderF3(data); renderCalendar(data); updateSelectionHelp(); applyRegistryView();
}
function enableRegistryCardExpansion(card) {
  card.addEventListener('click', event => {
    if (!registryListMode || event.target.closest('button, input, label, a')) return;
    const isExpanded = card.classList.toggle('is-expanded');
    card.setAttribute('aria-expanded', String(isExpanded));
  });
}

function renderF1(data) {
  const ordered = [...data.f1].sort((a,b) => b.date.localeCompare(a.date)); q('f1-count').textContent = ordered.length ? `${ordered.length} producció${ordered.length === 1 ? '' : 'ns'}` : ''; q('f1-empty').hidden = ordered.length > 0; q('f1-list').innerHTML = '';
  ordered.forEach(item => { const node = q('f1-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f1:${item.id}`, check = node.querySelector('.record-check'); card.id = `f1-${item.id}`; enableRegistryCardExpansion(card); check.checked = selectedRecords.has(key); check.onchange = () => { check.checked ? selectedRecords.add(key) : selectedRecords.delete(key); updateSelectionHelp(); }; node.querySelector('.card-date').textContent = new Intl.DateTimeFormat('ca-ES', { dateStyle: 'long' }).format(localDate(item.date)); node.querySelector('.values').innerHTML = [['Quantitat', `${item.liters} L`], ['Temperatura', item.temperature && `${item.temperature} °C`], ['pH', item.ph], ['Durada', item.days && `${item.days} dies`]].filter(([,v]) => v).map(([k,v]) => `<div><dt>${k}</dt><dd> ${v}</dd></div>`).join(''); node.querySelector('.recipe').textContent = f1Recipe(Number(item.liters)); node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : ''; (item.photos || []).forEach(photo => { const image = new Image(); image.src = photo; image.alt = 'Foto de la producció F1'; node.querySelector('.gallery').append(image); }); node.querySelector('.edit-button').onclick = () => editF1(item); node.querySelector('.delete-button').onclick = () => remove('f1', item.id); q('f1-list').append(node); });
}
function renderF2(data) {
  const ordered = [...data.f2].sort((a,b) => b.date.localeCompare(a.date)); q('f2-count').textContent = ordered.length ? `${ordered.length} prova${ordered.length === 1 ? '' : 'es'}` : ''; q('f2-empty').hidden = ordered.length > 0; q('f2-list').innerHTML = '';
  ordered.forEach(item => { const components = item.components || [{ name: item.fruit || 'Fruita', rate: 100 }], node = q('f2-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f2:${item.id}`, check = node.querySelector('.record-check'); card.id = `f2-${item.id}`; enableRegistryCardExpansion(card); check.checked = selectedRecords.has(key); check.onchange = () => { check.checked ? selectedRecords.add(key) : selectedRecords.delete(key); updateSelectionHelp(); }; node.querySelector('h3').textContent = item.name; node.querySelector('.card-date').textContent = `Embotellada: ${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'long' }).format(localDate(item.date))}`; node.querySelector('.base').textContent = baseName(item.f1Id, data); node.querySelector('.values').innerHTML = [['Quantitat', `${item.liters} L`], ['F2', item.days && `${item.days} dies`]].filter(([,v]) => v).map(([k,v]) => `<div><dt>${k}</dt><dd> ${v}</dd></div>`).join(''); node.querySelector('.recipe').textContent = f2Recipe(Number(item.liters), components); node.querySelector('.ingredients').textContent = item.ingredients ? `Notes d’ingredients: ${item.ingredients}` : ''; node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : ''; (item.photos || []).forEach(photo => { const image = new Image(); image.src = photo; image.alt = `Foto de ${item.name}`; node.querySelector('.gallery').append(image); }); node.querySelector('.edit-button').onclick = () => editF2(item); node.querySelector('.delete-button').onclick = () => remove('f2', item.id); node.querySelector('.pdf-button').onclick = () => pdf(item, data); node.querySelector('.word-button').onclick = () => word(item, data); q('f2-list').append(node); });
}
function f2ProductName(id, data) { return data.f2.find(item => item.id === id)?.name || 'Producte sense vincular'; }
function f2Name(id, data) { const batch = data.f2.find(item => item.id === id); return batch ? `F2: ${batch.name}` : 'F2: sense vincular'; }
function renderF3(data) { const ordered = [...data.f3].sort((a,b) => b.date.localeCompare(a.date)); q('f3-count').textContent = ordered.length ? `${ordered.length} conservació${ordered.length === 1 ? '' : 'ns'}` : ''; q('f3-empty').hidden = ordered.length > 0; q('f3-list').innerHTML = ''; ordered.forEach(item => { const node = q('f3-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f3:${item.id}`, check = node.querySelector('.record-check'), status = item.status || 'stock', statusCheck = node.querySelector('.status-check'); card.id = `f3-${item.id}`; enableRegistryCardExpansion(card); check.checked = selectedRecords.has(key); check.onchange = () => { check.checked ? selectedRecords.add(key) : selectedRecords.delete(key); updateSelectionHelp(); }; statusCheck.checked = status === 'consumed'; statusCheck.onchange = () => setF3Status(item.id, statusCheck.checked ? 'consumed' : 'stock'); node.querySelector('h3').textContent = `F3 · ${f2ProductName(item.f2Id, data)}`; node.querySelector('.card-date').textContent = `Filtrada: ${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'long' }).format(localDate(item.date))}`; node.querySelector('.base').textContent = f2Name(item.f2Id, data); node.querySelector('.values').innerHTML = [['Estat', status === 'consumed' ? 'Consumida' : 'En estoc'], ['Lot', item.lot], ['Quantitat', `${item.liters} L`], ['Ampolles', item.bottles], ['Temperatura', item.storageTemperature && `${item.storageTemperature} °C`], ['Consum preferent', item.bestBefore && new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.bestBefore))], ['Data de consum', item.consumedDate && new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.consumedDate))]].filter(([,v]) => v).map(([k,v]) => `<div><dt>${k}</dt><dd> ${v}</dd></div>`).join(''); node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : ''; (item.photos || []).forEach(photo => { const image = new Image(); image.src = photo; image.alt = 'Foto de la conservació F3'; node.querySelector('.gallery').append(image); }); node.querySelector('.edit-button').onclick = () => editF3(item); node.querySelector('.delete-button').onclick = () => remove('f3', item.id); q('f3-list').append(node); }); }
function editF1(item) { editingF1 = item.id; [['f1-date',item.date],['f1-liters',item.liters],['f1-temperature',item.temperature],['f1-ph',item.ph],['f1-days',item.days],['f1-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingF1Photos = [...(item.photos || [])]; q('f1-title').textContent = 'Edita la producció F1'; q('save-f1').textContent = 'Desa els canvis'; showF1Photos(); updateRecipes(); setView('production'); q('f1-form').scrollIntoView({ behavior: 'smooth' }); }
function editF2(item) { editingF2 = item.id; [['f2-f1-id',item.f1Id],['f2-name',item.name],['f2-date',item.date],['f2-liters',item.liters],['f2-days',item.days],['f2-ingredients',item.ingredients],['f2-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingPhotos = [...(item.photos || [])]; q('f2-title').textContent = 'Edita la prova F2'; q('save-f2').textContent = 'Desa els canvis'; showPhotos(); renderComponents(item.components || [{ name: item.fruit || 'Maduixa', rate: 100 }]); setView('production'); q('f2-form').scrollIntoView({ behavior: 'smooth' }); }
function editF3(item) { editingF3 = item.id; renderSelectors(getData()); [['f3-f2-id',item.f2Id],['f3-date',item.date],['f3-liters',item.liters],['f3-bottles',item.bottles],['f3-lot',item.lot],['f3-storage-temperature',item.storageTemperature],['f3-status',item.status || 'stock'],['f3-best-before',item.bestBefore],['f3-consumed-date',item.consumedDate],['f3-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingF3Photos = [...(item.photos || [])]; q('f3-title').textContent = 'Edita la conservació F3'; q('save-f3').textContent = 'Desa els canvis'; showF3Photos(); setView('production'); q('f3-form').scrollIntoView({ behavior: 'smooth' }); }
function setF3Status(id, status) { const data = getData(); data.f3 = data.f3.map(item => item.id === id ? { ...item, status, consumedDate: status === 'consumed' ? item.consumedDate || today() : '' } : item); saveData(data); render(); }
function remove(type, id) { if (!confirm('Vols eliminar aquest registre?')) return; const data = getData(); data[type] = data[type].filter(item => item.id !== id); selectedRecords.delete(`${type}:${id}`); saveData(data); render(); }
function report(item, data) { const components = item.components || [{ name: item.fruit || 'Fruita', rate: 100 }]; return [['Base F1',baseName(item.f1Id,data)],['Data d’embotellat',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat F2',`${item.liters} L`],['Recepta F2',f2Recipe(Number(item.liters),components)],['Durada de F2',item.days && `${item.days} dies`],['Notes d’ingredients',item.ingredients],['Notes',item.notes]].filter(([,v])=>v); }
function pdfHeader(doc,title,subtitle) { doc.setFillColor(49,93,66);doc.rect(0,0,210,34,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(19);doc.text(title,16,16);doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text(subtitle,16,25);doc.setTextColor(37,50,40);return 44; }
function pdfRows(doc,rows,y) { const standard=rows.filter(([label])=>!label.startsWith('Notes')),notes=rows.filter(([label])=>label.startsWith('Notes'));standard.forEach(([label,value])=>{const labelLines=doc.splitTextToSize(label,42),valueLines=doc.splitTextToSize(String(value),115),height=Math.max(14,8+Math.max(labelLines.length,valueLines.length)*4.5);if(y+height>278){doc.addPage();y=22;}doc.setFillColor(247,244,235);doc.rect(16,y,54,height,'F');doc.setDrawColor(216,210,195);doc.rect(16,y,178,height,'S');doc.line(70,y,70,y+height);doc.setFont('helvetica','bold');doc.setTextColor(49,93,66);doc.setFontSize(9);doc.text(labelLines,22,y+7);doc.setFont('helvetica','normal');doc.setTextColor(37,50,40);doc.setFontSize(10);doc.text(valueLines,76,y+7);y+=height;});notes.forEach(([label,value])=>{const lines=doc.splitTextToSize(String(value),164),height=Math.max(28,15+lines.length*4.5);if(y+height+6>278){doc.addPage();y=22;}y+=6;doc.setFillColor(247,244,235);doc.roundedRect(16,y,178,height,3,3,'F');doc.setDrawColor(216,210,195);doc.roundedRect(16,y,178,height,3,3,'S');doc.setFont('helvetica','bold');doc.setTextColor(49,93,66);doc.setFontSize(9);doc.text(label,23,y+8);doc.setFont('helvetica','normal');doc.setTextColor(37,50,40);doc.setFontSize(10);doc.text(lines,23,y+16);y+=height+6;});return y; }
function pdfFooter(doc) { const pages=doc.getNumberOfPages();for(let page=1;page<=pages;page++){doc.setPage(page);doc.setTextColor(49,93,66);doc.setFontSize(8);doc.text(`Diari de kombutxa · MARTA · ${page}/${pages}`,16,290);} }
const imageSize = source => new Promise(resolve => { const image = new Image(); image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight }); image.onerror = () => resolve({ width: 1, height: 1 }); image.src = source; });
async function pdf(item,data) { const { jsPDF } = window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});let y=pdfHeader(doc,'Informe de prova F2',item.name);y=pdfRows(doc,report(item,data),y);for(const [index,photo] of (item.photos||[]).entries()){const {width,height}=await imageSize(photo),scale=Math.min(150/width,115/height,1),photoWidth=width*scale,photoHeight=height*scale;if(y+photoHeight+12>278){doc.addPage();y=22;}doc.setFont('helvetica','bold');doc.setTextColor(49,93,66);doc.setFontSize(10);doc.text(`Foto ${index+1}`,16,y);y+=5;doc.addImage(photo,photo.startsWith('data:image/png')?'PNG':'JPEG',16,y,photoWidth,photoHeight);y+=photoHeight+7;}pdfFooter(doc);doc.save(`${fileName(item.name)}.pdf`); }
function wordParts(title,subtitle,rows,docx) { const {Paragraph,TextRun,Table,TableRow,TableCell,WidthType,ShadingType,BorderStyle}=docx,border={style:BorderStyle.SINGLE,size:6,color:'D8D2C3'},standard=rows.filter(([label])=>!label.startsWith('Notes')),notes=rows.filter(([label])=>label.startsWith('Notes'));const banner=new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE},insideHorizontal:{style:BorderStyle.NONE},insideVertical:{style:BorderStyle.NONE}},rows:[new TableRow({children:[new TableCell({shading:{type:ShadingType.CLEAR,fill:'315D42'},margins:{top:180,bottom:180,left:220,right:220},children:[new Paragraph({children:[new TextRun({text:title,bold:true,size:32,color:'FFFFFF'})],spacing:{after:70}}),new Paragraph({children:[new TextRun({text:subtitle,size:20,color:'FFFFFF'})]})]})]})]});const dataTable=new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:{top:border,bottom:border,left:border,right:border,insideHorizontal:border,insideVertical:border},rows:standard.map(([label,value])=>new TableRow({children:[new TableCell({width:{size:28,type:WidthType.PERCENTAGE},shading:{type:ShadingType.CLEAR,fill:'F7F4EB'},margins:{top:110,bottom:110,left:150,right:130},children:[new Paragraph({children:[new TextRun({text:label,bold:true,color:'315D42',size:18})]})]}),new TableCell({width:{size:72,type:WidthType.PERCENTAGE},margins:{top:110,bottom:110,left:150,right:150},children:[new Paragraph({children:[new TextRun({text:String(value),size:20,color:'253228'})]})]})]}))});const noteBlocks=notes.flatMap(([label,value])=>[new Paragraph({text:'',spacing:{after:100}}),new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:{top:border,bottom:border,left:border,right:border,insideHorizontal:border,insideVertical:border},rows:[new TableRow({children:[new TableCell({shading:{type:ShadingType.CLEAR,fill:'F7F4EB'},margins:{top:140,bottom:140,left:180,right:180},children:[new Paragraph({children:[new TextRun({text:label,bold:true,color:'315D42',size:19})],spacing:{after:80}}),new Paragraph({children:[new TextRun({text:String(value),size:21,color:'253228'})]})]})]})]})]);return [banner,new Paragraph({text:'',spacing:{after:120}}),dataTable,...noteBlocks]; }
async function word(item,data) { if(!window.docx){alert('No s’ha pogut carregar l’exportació Word.');return;}const {Document,Packer,Paragraph,ImageRun}=window.docx,children=wordParts('Informe de prova F2',item.name,report(item,data),window.docx);for(const [index,photo] of (item.photos||[]).entries()){const bytes=new Uint8Array(await(await fetch(photo)).arrayBuffer()),{width,height}=await imageSize(photo),scale=Math.min(400/width,280/height,1),photoWidth=Math.round(width*scale),photoHeight=Math.round(height*scale);children.push(new Paragraph({text:`Foto ${index+1}`,heading:'Heading2',spacing:{before:160,after:80}}),new Paragraph({children:[new ImageRun({data:bytes,transformation:{width:photoWidth,height:photoHeight}})]}));}const blob=await Packer.toBlob(new Document({sections:[{properties:{page:{margin:{top:720,right:720,bottom:720,left:720}}},children}]}));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${fileName(item.name)}.docx`;a.click();URL.revokeObjectURL(a.href); }
function selectedItems(data) { return [...selectedRecords].map(key => { const [type, id] = key.split(':'); const item = data[type]?.find(record => record.id === id); return item ? { type, item } : null; }).filter(Boolean); }
function f1Report(item) { return [['Data d’inici',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat F1',`${item.liters} L`],['Recepta F1',f1Recipe(Number(item.liters))],['Temperatura',item.temperature && `${item.temperature} °C`],['pH',item.ph],['Durada',item.days && `${item.days} dies`],['Notes',item.notes]].filter(([,value]) => value); }
function f3Report(item, data) { return [['Estat',item.status === 'consumed' ? 'Consumida' : 'En estoc'],['Lot / referència',item.lot],['Prova F2 d’origen',f2Name(item.f2Id,data)],['Data de filtratge',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat a la nevera',`${item.liters} L`],['Ampolles',item.bottles],['Temperatura de nevera',item.storageTemperature && `${item.storageTemperature} °C`],['Consum preferent',item.bestBefore && new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.bestBefore))],['Data de consum',item.consumedDate && new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.consumedDate))],['Notes',item.notes]].filter(([,value]) => value); }
function recordReport(entry, data) { if (entry.type === 'f1') return { title: `Producció F1 · ${entry.item.liters} L`, rows: f1Report(entry.item) }; if (entry.type === 'f3') return { title: `F3 · ${f2ProductName(entry.item.f2Id, data)}`, rows: f3Report(entry.item, data) }; return { title: `Prova F2 · ${entry.item.name}`, rows: report(entry.item, data) }; }
function updateSelectionHelp() { const selected = selectedRecords.size; q('selection-help').textContent = selected ? `${selected} registre${selected === 1 ? '' : 's'} seleccionat${selected === 1 ? '' : 's'}.` : 'No hi ha cap registre seleccionat.'; }
function applyRegistryView() { q('f1-list').classList.toggle('is-list',registryListMode); q('f2-list').classList.toggle('is-list',registryListMode); q('f3-list').classList.toggle('is-list',registryListMode); q('registry-view-select').value = registryListMode ? 'list' : 'cards'; }
function applySelectionAction(action) { const data = getData(); if (action === 'clear') { selectedRecords.clear(); q('comparison-table').innerHTML = ''; q('comparison-panel').hidden = true; } else if (action) { const types = action === 'all' ? ['f1','f2','f3'] : [action]; selectedRecords = new Set(types.flatMap(type => data[type].map(item => `${type}:${item.id}`))); } q('record-selection-action').value = ''; render(); }
function chronologicalEntries(data) { const phaseOrder = { f1: 1, f2: 2, f3: 3 }; return selectedItems(data).sort((a,b) => phaseOrder[a.type] - phaseOrder[b.type] || (a.item.date || '').localeCompare(b.item.date || '')); }
function registerTableRows(entries, data) { return entries.map(entry => { const item = entry.item; if (entry.type === 'f1') return [new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(item.date)), 'F1', 'Base de kombutxa', `${item.liters} L`, [item.temperature && `${item.temperature} °C`, item.ph && `pH ${item.ph}`, item.days && `${item.days} dies`].filter(Boolean).join(' · ') || '—', item.notes || '—']; if (entry.type === 'f2') return [new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(item.date)), 'F2', item.name, `${item.liters} L`, item.days ? `${item.days} dies` : '—', [item.ingredients, item.notes].filter(Boolean).join(' · ') || '—']; return [new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(item.date)), 'F3', [f2ProductName(item.f2Id,data), item.lot && `Lot: ${item.lot}`].filter(Boolean).join(' · '), `${item.liters} L`, item.status === 'consumed' ? `Consumida${item.consumedDate ? ` · ${new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(item.consumedDate))}` : ''}` : 'En estoc', item.notes || '—']; }); }
function exportSelectedPdf() { const data=getData(),entries=chronologicalEntries(data);if(!entries.length){alert('Selecciona almenys un registre.');return;}const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),headers=['Data','Fase','Producte / lot','Quantitat','Estat / informació','Notes'],widths=[28,17,57,25,55,78],groups=[['f1','F1 · Producció'],['f2','F2 · Proves'],['f3','F3 · Conservació']].map(([type,title])=>({title,rows:registerTableRows(entries.filter(entry=>entry.type===type),data)})).filter(group=>group.rows.length);let y=31;const pageHeader=()=>{doc.setFillColor(49,93,66);doc.rect(0,0,297,21,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Registre de kombutxa',16,13);};const tableHeader=()=>{let x=16;headers.forEach((header,index)=>{doc.setFillColor(232,238,229);doc.rect(x,y,widths[index],8,'F');doc.setDrawColor(216,210,195);doc.rect(x,y,widths[index],8,'S');doc.setTextColor(37,50,40);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(header,x+2,y+5);x+=widths[index];});y+=8;};pageHeader();groups.forEach(group=>{if(y+17>196){doc.addPage();y=18;pageHeader();}doc.setFillColor(49,93,66);doc.roundedRect(16,y,260,8,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(group.title,20,y+5.4);y+=8;tableHeader();group.rows.forEach((row,rowIndex)=>{const lines=row.map((cell,index)=>doc.splitTextToSize(String(cell),widths[index]-4)),height=Math.max(9,...lines.map(cellLines=>cellLines.length*3.7+4));if(y+height>196){doc.addPage();y=18;pageHeader();doc.setFillColor(49,93,66);doc.roundedRect(16,y,260,8,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(group.title,20,y+5.4);y+=8;tableHeader();}let x=16;row.forEach((cell,index)=>{doc.setFillColor(rowIndex%2?250:247,rowIndex%2?248:244,rowIndex%2?240:235);doc.rect(x,y,widths[index],height,'F');doc.setDrawColor(216,210,195);doc.rect(x,y,widths[index],height,'S');doc.setTextColor(37,50,40);doc.setFont('helvetica',index===1?'bold':'normal');doc.setFontSize(8);doc.text(lines[index],x+2,y+5);x+=widths[index];});y+=height;});y+=8;});const pages=doc.getNumberOfPages();for(let page=1;page<=pages;page++){doc.setPage(page);doc.setTextColor(49,93,66);doc.setFontSize(8);doc.text(`Diari de kombutxa · MARTA · ${page}/${pages}`,16,204);}doc.save('registre-kombutxa-sanitat.pdf'); }
function registerWordTable(rows, docx) { const {Paragraph,TextRun,Table,TableRow,TableCell,WidthType,ShadingType,BorderStyle}=docx,border={style:BorderStyle.SINGLE,size:6,color:'D8D2C3'},headers=['Data','Fase','Producte / lot','Quantitat','Estat / informació','Notes'],makeCell=(text,header=false)=>new TableCell({shading:{type:ShadingType.CLEAR,fill:header?'315D42':'F7F4EB'},margins:{top:90,bottom:90,left:110,right:110},children:[new Paragraph({children:[new TextRun({text:String(text),bold:header,size:header?17:16,color:header?'FFFFFF':'253228'})]})]}),tableRows=[new TableRow({children:headers.map(header=>makeCell(header,true))}),...rows.map(row=>new TableRow({children:row.map(value=>makeCell(value))}))];return new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:{top:border,bottom:border,left:border,right:border,insideHorizontal:border,insideVertical:border},rows:tableRows}); }
async function exportSelectedWord() { const data=getData(),entries=chronologicalEntries(data);if(!entries.length){alert('Selecciona almenys un registre.');return;}if(!window.docx){alert('No s’ha pogut carregar l’exportació Word.');return;}const {Document,Packer,Paragraph,TextRun}=window.docx,groups=[['f1','F1 · Producció'],['f2','F2 · Proves'],['f3','F3 · Conservació']].map(([type,title])=>({title,rows:registerTableRows(entries.filter(entry=>entry.type===type),data)})).filter(group=>group.rows.length),children=[new Paragraph({children:[new TextRun({text:'Registre de kombutxa',bold:true,size:34,color:'315D42'})],spacing:{after:90}}),new Paragraph({children:[new TextRun({text:'F1 · F2 · F3, ordenat cronològicament dins de cada fase',size:20,color:'253228'})],spacing:{after:180}})];groups.forEach(group=>children.push(new Paragraph({children:[new TextRun({text:group.title,bold:true,size:24,color:'315D42'})],spacing:{before:180,after:90}}),registerWordTable(group.rows,window.docx)));const blob=await Packer.toBlob(new Document({sections:[{properties:{page:{size:{orientation:'landscape'},margin:{top:720,right:720,bottom:720,left:720}}},children}]})),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='registre-kombutxa-sanitat.docx';link.click();URL.revokeObjectURL(link.href); }
const escapeHtml = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function compareSelected() { const data = getData(), entries = selectedItems(data).filter(entry => entry.type === 'f2'); if (entries.length < 2) { alert('Selecciona almenys dues proves F2 per comparar-les.'); return; } const fields = [['Data',entry => new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(entry.item.date))],['Quantitat',entry => `${entry.item.liters} L`],['Dies F2',entry => entry.item.days ? `${entry.item.days} dies` : '—'],['Recepta',entry => f2Recipe(Number(entry.item.liters),entry.item.components || [{name:entry.item.fruit || 'Fruita',rate:100}])],['Notes ingredients',entry => entry.item.ingredients || '—'],['Notes de prova',entry => entry.item.notes || '—']]; q('comparison-table').innerHTML = `<div class="comparison-table-wrap"><table class="comparison-table"><thead><tr><th>Camp</th>${entries.map(entry => `<th>${escapeHtml(entry.item.name)}</th>`).join('')}</tr></thead><tbody>${fields.map(([label,getValue]) => `<tr><th>${label}</th>${entries.map(entry => `<td>${escapeHtml(getValue(entry))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; q('comparison-panel').hidden = false; q('comparison-panel').scrollIntoView({behavior:'smooth'}); }
function setView(view) { document.querySelectorAll('[data-view]').forEach(panel => panel.hidden = panel.dataset.view !== view || (panel.id === 'comparison-panel' && !q('comparison-table').innerHTML)); document.querySelectorAll('[data-view-button]').forEach(button => { const active = button.dataset.viewButton === view; button.classList.toggle('is-active',active); button.setAttribute('aria-selected',String(active)); }); }
function openCalendarRecord(id) { setView('registry'); const card = q(id); if (!card) return; card.classList.add('is-expanded'); card.setAttribute('aria-expanded', 'true'); requestAnimationFrame(() => card.scrollIntoView({ behavior: 'smooth', block: 'center' })); }
function renderCalendar(data) { const label=new Intl.DateTimeFormat('ca-ES',{month:'long',year:'numeric'}).format(calendarCursor);q('calendar-month').textContent=label.charAt(0).toUpperCase()+label.slice(1);const days=q('calendar-days');days.innerHTML='';const start=new Date(calendarCursor),first=new Date(start);first.setDate(1-((start.getDay()+6)%7));for(let i=0;i<42;i++){const date=new Date(first);date.setDate(first.getDate()+i);const key=isoDate(date),cell=document.createElement('div');cell.className=`calendar-day${date.getMonth()!==calendarCursor.getMonth()?' is-outside':''}`;cell.innerHTML=`<span class="day-number">${date.getDate()}</span>`;[...data.f1.map(x=>({date:x.date,label:`F1 · ${x.liters} L`,id:`f1-${x.id}`})),...data.f2.map(x=>({date:x.date,label:`F2 · ${x.name}`,id:`f2-${x.id}`})),...data.f3.map(x=>({date:x.date,label:`F3 · ${x.liters} L a la nevera`,id:`f3-${x.id}`}))].filter(x=>x.date===key).forEach(event=>{const button=document.createElement('button');button.className='calendar-event';button.textContent=event.label;button.onclick=()=>openCalendarRecord(event.id);cell.append(button);});days.append(cell);} }
q('f1-form').onsubmit=event=>{event.preventDefault();const data=getData(),item={id:editingF1||crypto.randomUUID(),date:q('f1-date').value,liters:q('f1-liters').value,temperature:q('f1-temperature').value,ph:q('f1-ph').value,days:q('f1-days').value,notes:q('f1-notes').value.trim(),photos:pendingF1Photos};data.f1=editingF1?data.f1.map(x=>x.id===editingF1?item:x):[item,...data.f1];saveData(data);localStorage.removeItem(draftKey);resetF1();render();};
q('f2-form').onsubmit=event=>{event.preventDefault();const data=getData(),item={id:editingF2||crypto.randomUUID(),f1Id:q('f2-f1-id').value,name:q('f2-name').value.trim(),date:q('f2-date').value,liters:q('f2-liters').value,components:formComponents(),days:q('f2-days').value,ingredients:q('f2-ingredients').value.trim(),notes:q('f2-notes').value.trim(),photos:pendingPhotos};data.f2=editingF2?data.f2.map(x=>x.id===editingF2?item:x):[item,...data.f2];saveData(data);localStorage.removeItem(draftKey);resetF2();render();};
q('f3-form').onsubmit=event=>{event.preventDefault();const data=getData(),status=q('f3-status').value,item={id:editingF3||crypto.randomUUID(),f2Id:q('f3-f2-id').value,date:q('f3-date').value,liters:q('f3-liters').value,bottles:q('f3-bottles').value,lot:q('f3-lot').value.trim(),storageTemperature:q('f3-storage-temperature').value,status,bestBefore:q('f3-best-before').value,consumedDate:status === 'consumed' ? q('f3-consumed-date').value || today() : '',notes:q('f3-notes').value.trim(),photos:pendingF3Photos};data.f3=editingF3?data.f3.map(x=>x.id===editingF3?item:x):[item,...data.f3];saveData(data);resetF3();render();};
const compactPhoto = file => new Promise(resolve => { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 1280 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', 0.8)); }; image.onerror = () => resolve(reader.result); image.src = reader.result; }; reader.readAsDataURL(file); });
q('f2-photos').onchange=async()=>{const photos=await Promise.all([...q('f2-photos').files].map(compactPhoto));pendingPhotos.push(...photos);q('f2-photos').value='';showPhotos();};
q('f1-photos').onchange=async()=>{const photos=await Promise.all([...q('f1-photos').files].map(compactPhoto));pendingF1Photos.push(...photos);q('f1-photos').value='';showF1Photos();};
q('f3-photos').onchange=async()=>{const photos=await Promise.all([...q('f3-photos').files].map(compactPhoto));pendingF3Photos.push(...photos);q('f3-photos').value='';showF3Photos();};
saveDraft = saveDraftUpdated; resetF1 = resetF1Updated; resetF2 = resetF2Updated; resetF3 = resetF3Updated; renderF1 = renderF1Updated; renderF2 = renderF2Updated; renderF3 = renderF3Updated; editF1 = editF1Updated; editF2 = editF2Updated; editF3 = editF3Updated; f1Report = f1ReportUpdated; report = reportUpdated; f3Report = f3ReportUpdated; registerTableRows = registerTableRowsUpdated; applyRegistryView = applyRegistryViewUpdated; applySelectionAction = applySelectionActionUpdated; setView = setViewUpdated;
q('clear-f1').onclick=()=>{localStorage.removeItem(draftKey);resetF1();};q('clear-f2').onclick=()=>{localStorage.removeItem(draftKey);resetF2();};q('clear-f3').onclick=()=>{localStorage.removeItem(draftKey);resetF3();render();};q('add-ingredient').onclick=()=>renderComponents([...formComponents(),{ name: 'Gingebre', rate: 10 }]);['f1-liters','f2-liters'].forEach(id=>q(id).oninput=updateRecipes);q('f3-f2-id').onchange=()=>{const batch=getData().f2.find(item=>item.id===q('f3-f2-id').value);if(batch&&!q('f3-liters').value)q('f3-liters').value=batch.liters;saveDraft();};q('previous-month').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar(getData());};q('next-month').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar(getData());};q('registry-view-select').onchange=()=>{registryListMode=q('registry-view-select').value==='list';localStorage.setItem('diari-kombutxa-registry-view',registryListMode?'list':'cards');applyRegistryView();};q('record-selection-action').onchange=()=>applySelectionAction(q('record-selection-action').value);q('record-export-action').onchange=()=>{const action=q('record-export-action').value;if(action==='pdf')exportSelectedPdf();if(action==='word')exportSelectedWord();q('record-export-action').value='';};q('close-comparison').onclick=()=>{q('comparison-table').innerHTML='';q('comparison-panel').hidden=true;};document.querySelectorAll('[data-view-button]').forEach(button=>button.onclick=()=>setView(button.dataset.viewButton));document.addEventListener('input', event => { if (event.target.closest('#f1-form') || event.target.closest('#f2-form') || event.target.closest('#f3-form')) saveDraft(); });window.addEventListener('kombutxa-cloud-data', () => { if (!editingF1 && !editingF2 && !editingF3) render(); });resetF1();resetF2();resetF3();render();restoreDraft();setView('production');
function exportSelectedPdf() { const data=getData(),entries=chronologicalEntries(data);if(!entries.length){alert('Selecciona almenys un registre.');return;}const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'}),headers=['Data','Fase','Producte / lot','Quantitat','Estat / informació','Notes'],widths=[24,14,39,20,38,43],groups=[['f1','F1 · Producció'],['f2','F2 · Proves'],['f3','F3 · Conservació']].map(([type,title])=>({title,rows:registerTableRows(entries.filter(entry=>entry.type===type),data)})).filter(group=>group.rows.length);let y=31;const pageHeader=()=>{doc.setFillColor(49,93,66);doc.rect(0,0,210,21,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('Registre de kombutxa',16,13);};const tableHeader=()=>{let x=16;headers.forEach((header,index)=>{doc.setFillColor(232,238,229);doc.rect(x,y,widths[index],8,'F');doc.setDrawColor(216,210,195);doc.rect(x,y,widths[index],8,'S');doc.setTextColor(37,50,40);doc.setFont('helvetica','bold');doc.setFontSize(7);doc.text(header,x+2,y+5);x+=widths[index];});y+=8;};pageHeader();groups.forEach(group=>{if(y+17>278){doc.addPage();y=31;pageHeader();}doc.setFillColor(49,93,66);doc.roundedRect(16,y,178,8,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(group.title,20,y+5.4);y+=8;tableHeader();group.rows.forEach((row,rowIndex)=>{const lines=row.map((cell,index)=>doc.splitTextToSize(String(cell),widths[index]-4)),height=Math.max(9,...lines.map(cellLines=>cellLines.length*3.7+4));if(y+height>278){doc.addPage();y=31;pageHeader();doc.setFillColor(49,93,66);doc.roundedRect(16,y,178,8,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(group.title,20,y+5.4);y+=8;tableHeader();}let x=16;row.forEach((cell,index)=>{doc.setFillColor(rowIndex%2?250:247,rowIndex%2?248:244,rowIndex%2?240:235);doc.rect(x,y,widths[index],height,'F');doc.setDrawColor(216,210,195);doc.rect(x,y,widths[index],height,'S');doc.setTextColor(37,50,40);doc.setFont('helvetica',index===1?'bold':'normal');doc.setFontSize(7);doc.text(lines[index],x+2,y+5);x+=widths[index];});y+=height;});y+=8;});const pages=doc.getNumberOfPages();for(let page=1;page<=pages;page++){doc.setPage(page);doc.setTextColor(49,93,66);doc.setFontSize(8);doc.text(`Diari de kombutxa · MARTA · ${page}/${pages}`,16,290);}doc.save('registre-kombutxa-sanitat.pdf'); }
async function exportSelectedWord() { const data=getData(),entries=chronologicalEntries(data);if(!entries.length){alert('Selecciona almenys un registre.');return;}if(!window.docx){alert('No s’ha pogut carregar l’exportació Word.');return;}const {Document,Packer,Paragraph,TextRun}=window.docx,groups=[['f1','F1 · Producció'],['f2','F2 · Proves'],['f3','F3 · Conservació']].map(([type,title])=>({title,rows:registerTableRows(entries.filter(entry=>entry.type===type),data)})).filter(group=>group.rows.length),children=[new Paragraph({children:[new TextRun({text:'Registre de kombutxa',bold:true,size:34,color:'315D42'})],spacing:{after:90}}),new Paragraph({children:[new TextRun({text:'F1 · F2 · F3, ordenat cronològicament dins de cada fase',size:20,color:'253228'})],spacing:{after:180}})];groups.forEach(group=>children.push(new Paragraph({children:[new TextRun({text:group.title,bold:true,size:24,color:'315D42'})],spacing:{before:180,after:90}}),registerWordTable(group.rows,window.docx)));const blob=await Packer.toBlob(new Document({sections:[{properties:{page:{margin:{top:720,right:720,bottom:720,left:720}}},children}]})),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='registre-kombutxa-sanitat.docx';link.click();URL.revokeObjectURL(link.href); }
if (window.jspdf?.jsPDF) { const originalPdfText = window.jspdf.jsPDF.prototype.text, originalPdfRect = window.jspdf.jsPDF.prototype.rect; window.jspdf.jsPDF.prototype.text = function(text, ...args) { if (text === 'Registre de kombutxa' && this.getCurrentPageInfo().pageNumber > 1) return this; return originalPdfText.call(this, text, ...args); }; window.jspdf.jsPDF.prototype.rect = function(x, y, width, height, ...args) { if (x === 0 && y === 0 && width === 210 && height === 21 && this.getCurrentPageInfo().pageNumber > 1) return this; return originalPdfRect.call(this, x, y, width, height, ...args); }; }
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');

/* Lots i registre sanitari: versió compacta */
function lotCode(phase, now = new Date()) {
  const pad = value => String(value).padStart(2, '0');
  return `${phase}-${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}`;
}
function lotLabel(item) { return item.lot ? `Lot: ${item.lot}` : 'Lot: sense assignar'; }
function formatRecordDate(value, prefix = '') { return `${prefix}${new Intl.DateTimeFormat('ca-ES', { dateStyle: 'long' }).format(localDate(value))}`; }
function valuesMarkup(values) { return values.filter(([, value]) => value).map(([label, value]) => `<div><dt>${label}</dt><dd> ${value}</dd></div>`).join(''); }
function appendPhotos(node, photos, alt) { (photos || []).forEach(photo => { const image = new Image(); image.src = photo; image.alt = alt; node.querySelector('.gallery').append(image); }); }
function bindSelection(node, key) { const check = node.querySelector('.record-check'); check.checked = selectedRecords.has(key); check.onchange = () => { check.checked ? selectedRecords.add(key) : selectedRecords.delete(key); updateSelectionHelp(); }; }

function saveDraftUpdated() {
  const saveFields = ids => ids.reduce((out, id) => ({ ...out, [id]: q(id).value }), {});
  localStorage.setItem(draftKey, JSON.stringify({
    f1: saveFields(['f1-date','f1-lot','f1-liters','f1-temperature','f1-ph','f1-days','f1-notes']),
    f2: saveFields(['f2-f1-id','f2-name','f2-date','f2-lot','f2-liters','f2-days','f2-ingredients','f2-notes']),
    f3: saveFields(['f3-f2-id','f3-date','f3-liters','f3-bottles','f3-lot','f3-storage-temperature','f3-status','f3-best-before','f3-consumed-date','f3-notes']),
    components: formComponents()
  }));
}
function resetF1Updated() { editingF1 = null; pendingF1Photos = []; q('f1-form').reset(); q('f1-date').value = today(); q('f1-lot').value = lotCode('F1'); q('f1-title').textContent = 'F1 · Producció'; q('save-f1').textContent = 'Desa la producció'; showF1Photos(); updateRecipes(); }
function resetF2Updated() { editingF2 = null; pendingPhotos = []; q('f2-form').reset(); q('f2-date').value = today(); q('f2-lot').value = lotCode('F2'); q('f2-title').textContent = 'F2 · Nova prova'; q('save-f2').textContent = 'Desa la prova'; showPhotos(); renderComponents([{ name: 'Maduixa', rate: 100 }]); }
function resetF3Updated() { editingF3 = null; pendingF3Photos = []; q('f3-form').reset(); q('f3-date').value = today(); q('f3-lot').value = lotCode('F3'); q('f3-status').value = 'stock'; q('f3-title').textContent = 'F3 · Conservació i consum'; q('save-f3').textContent = 'Desa la conservació'; showF3Photos(); }

function renderF1Updated(data) {
  const ordered = [...data.f1].sort((a, b) => b.date.localeCompare(a.date));
  q('f1-count').textContent = ordered.length ? `${ordered.length} producció${ordered.length === 1 ? '' : 'ns'}` : '';
  q('f1-empty').hidden = ordered.length > 0; q('f1-list').innerHTML = '';
  ordered.forEach(item => {
    const node = q('f1-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f1:${item.id}`;
    card.id = `f1-${item.id}`; enableRegistryCardExpansion(card); bindSelection(node, key);
    node.querySelector('.card-date').textContent = formatRecordDate(item.date);
    node.querySelector('.values').innerHTML = valuesMarkup([['Lot', item.lot || 'Sense lot'], ['Quantitat', `${item.liters} L`], ['Temperatura', item.temperature && `${item.temperature} °C`], ['pH', item.ph], ['Durada', item.days && `${item.days} dies`]]);
    node.querySelector('.recipe').textContent = f1Recipe(Number(item.liters)); node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : '';
    appendPhotos(node, item.photos, 'Foto de la producció F1'); node.querySelector('.edit-button').onclick = () => editF1(item); node.querySelector('.delete-button').onclick = () => remove('f1', item.id); q('f1-list').append(node);
  });
}
function renderF2Updated(data) {
  const ordered = [...data.f2].sort((a, b) => b.date.localeCompare(a.date));
  q('f2-count').textContent = ordered.length ? `${ordered.length} prova${ordered.length === 1 ? '' : 'es'}` : '';
  q('f2-empty').hidden = ordered.length > 0; q('f2-list').innerHTML = '';
  ordered.forEach(item => {
    const components = item.components || [{ name: item.fruit || 'Fruita', rate: 100 }], node = q('f2-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f2:${item.id}`;
    card.id = `f2-${item.id}`; enableRegistryCardExpansion(card); bindSelection(node, key);
    node.querySelector('h3').textContent = `F2 · ${item.name}`; node.querySelector('.card-date').textContent = formatRecordDate(item.date, 'Embotellada: ');
    node.querySelector('.base').textContent = `Producte: ${item.name} · ${baseName(item.f1Id, data)}`;
    node.querySelector('.values').innerHTML = valuesMarkup([['Lot', item.lot || 'Sense lot'], ['Quantitat', `${item.liters} L`], ['F2', item.days && `${item.days} dies`]]);
    node.querySelector('.recipe').textContent = f2Recipe(Number(item.liters), components); node.querySelector('.ingredients').textContent = item.ingredients ? `Notes d’ingredients: ${item.ingredients}` : ''; node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : '';
    appendPhotos(node, item.photos, `Foto de ${item.name}`); node.querySelector('.edit-button').onclick = () => editF2(item); node.querySelector('.delete-button').onclick = () => remove('f2', item.id); q('f2-list').append(node);
  });
}
function renderF3Card(item, data, consumed) {
  const node = q(consumed ? 'f3-consumed-template' : 'f3-template').content.cloneNode(true), card = node.querySelector('.batch-card'), key = `f3:${item.id}`, target = q(consumed ? 'f3-consumed-list' : 'f3-stock-list');
  card.id = `f3-${item.id}`; enableRegistryCardExpansion(card); if (!consumed) bindSelection(node, key);
  const product = f2ProductName(item.f2Id, data);
  node.querySelector('h3').textContent = `F3 · ${product}`; node.querySelector('.card-date').textContent = formatRecordDate(item.date, 'Filtrada: ');
  node.querySelector('.base').textContent = `Producte: ${product} · ${f2Name(item.f2Id, data)}`;
  node.querySelector('.values').innerHTML = valuesMarkup([['Estat', consumed ? 'Consumida' : 'En estoc'], ['Lot', item.lot || 'Sense lot'], ['Quantitat', `${item.liters} L`], ['Ampolles', item.bottles], ['Temperatura', item.storageTemperature && `${item.storageTemperature} °C`], ['Consum preferent', item.bestBefore && new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.bestBefore))], ['Data de consum', item.consumedDate && new Intl.DateTimeFormat('ca-ES', { dateStyle: 'medium' }).format(localDate(item.consumedDate))]]);
  node.querySelector('.notes').textContent = item.notes ? `Notes: ${item.notes}` : ''; appendPhotos(node, item.photos, 'Foto de la conservació F3'); node.querySelector('.edit-button').onclick = () => editF3(item);
  if (!consumed) node.querySelector('.delete-button').onclick = () => remove('f3', item.id); target.append(node);
}
function renderF3Updated(data) {
  const stock = data.f3.filter(item => (item.status || 'stock') !== 'consumed').sort((a, b) => b.date.localeCompare(a.date));
  const consumed = data.f3.filter(item => item.status === 'consumed').sort((a, b) => (b.consumedDate || b.date).localeCompare(a.consumedDate || a.date));
  [['stock', stock], ['consumed', consumed]].forEach(([type, items]) => { q(`f3-${type}-count`).textContent = items.length ? `${items.length} registre${items.length === 1 ? '' : 's'}` : ''; q(`f3-${type}-empty`).hidden = items.length > 0; q(`f3-${type}-list`).innerHTML = ''; items.forEach(item => renderF3Card(item, data, type === 'consumed')); });
  renderRegistrySummary(data);
}
function editF1Updated(item) { editingF1 = item.id; [['f1-date',item.date],['f1-lot',item.lot || lotCode('F1')],['f1-liters',item.liters],['f1-temperature',item.temperature],['f1-ph',item.ph],['f1-days',item.days],['f1-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingF1Photos = [...(item.photos || [])]; q('f1-title').textContent = 'Edita la producció F1'; q('save-f1').textContent = 'Desa els canvis'; showF1Photos(); updateRecipes(); setView('production'); setProductionPhase('f1'); q('f1-form').scrollIntoView({ behavior: 'smooth' }); }
function editF2Updated(item) { editingF2 = item.id; [['f2-f1-id',item.f1Id],['f2-name',item.name],['f2-date',item.date],['f2-lot',item.lot || lotCode('F2')],['f2-liters',item.liters],['f2-days',item.days],['f2-ingredients',item.ingredients],['f2-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingPhotos = [...(item.photos || [])]; q('f2-title').textContent = 'Edita la prova F2'; q('save-f2').textContent = 'Desa els canvis'; showPhotos(); renderComponents(item.components || [{ name: item.fruit || 'Maduixa', rate: 100 }]); setView('production'); setProductionPhase('f2'); q('f2-form').scrollIntoView({ behavior: 'smooth' }); }
function f1ReportUpdated(item) { return [['Lot / referència',item.lot],['Data d’inici',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat F1',`${item.liters} L`],['Recepta F1',f1Recipe(Number(item.liters))],['Temperatura',item.temperature && `${item.temperature} °C`],['pH',item.ph],['Durada',item.days && `${item.days} dies`],['Notes',item.notes]].filter(([,value]) => value); }
function reportUpdated(item, data) { const components = item.components || [{ name: item.fruit || 'Fruita', rate: 100 }]; return [['Producte',item.name],['Lot / referència',item.lot],['Base F1',baseName(item.f1Id,data)],['Data d’embotellat',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat F2',`${item.liters} L`],['Recepta F2',f2Recipe(Number(item.liters),components)],['Durada de F2',item.days && `${item.days} dies`],['Notes d’ingredients',item.ingredients],['Notes',item.notes]].filter(([,v])=>v); }
function f3ReportUpdated(item, data) { return [['Producte',f2ProductName(item.f2Id,data)],['Estat',item.status === 'consumed' ? 'Consumida' : 'En estoc'],['Lot / referència',item.lot],['Prova F2 d’origen',f2Name(item.f2Id,data)],['Data de filtratge',new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.date))],['Quantitat a la nevera',`${item.liters} L`],['Ampolles',item.bottles],['Temperatura de nevera',item.storageTemperature && `${item.storageTemperature} °C`],['Consum preferent',item.bestBefore && new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.bestBefore))],['Data de consum',item.consumedDate && new Intl.DateTimeFormat('ca-ES',{dateStyle:'long'}).format(localDate(item.consumedDate))],['Notes',item.notes]].filter(([,value]) => value); }
function registerTableRowsUpdated(entries, data) { return entries.map(entry => { const item = entry.item, date = new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(item.date)); if (entry.type === 'f1') return [date,'F1',`Base de kombutxa · ${lotLabel(item)}`,`${item.liters} L`,[item.temperature && `${item.temperature} °C`,item.ph && `pH ${item.ph}`,item.days && `${item.days} dies`].filter(Boolean).join(' · ') || '—',item.notes || '—']; if (entry.type === 'f2') return [date,'F2',`Producte: ${item.name} · ${lotLabel(item)}`,`${item.liters} L`,item.days ? `${item.days} dies` : '—',[item.ingredients,item.notes].filter(Boolean).join(' · ') || '—']; return [date,'F3',`Producte: ${f2ProductName(item.f2Id,data)} · ${lotLabel(item)}`,`${item.liters} L`,item.status === 'consumed' ? `Consumida${item.consumedDate ? ` · ${new Intl.DateTimeFormat('ca-ES',{dateStyle:'medium'}).format(localDate(item.consumedDate))}` : ''}` : 'En estoc',item.notes || '—']; }); }
function applyRegistryViewUpdated() { ['f1-list','f2-list','f3-stock-list','f3-consumed-list'].forEach(id => q(id).classList.toggle('is-list', registryListMode)); q('registry-view-select').value = registryListMode ? 'list' : 'cards'; }
function applySelectionActionUpdated(action) { const data = getData(); if (action === 'clear') { selectedRecords.clear(); q('comparison-table').innerHTML = ''; q('comparison-panel').hidden = true; } else if (action) { const types = action === 'all' ? ['f1','f2','f3'] : [action]; selectedRecords = new Set(types.flatMap(type => (type === 'f3' ? data.f3.filter(item => (item.status || 'stock') !== 'consumed') : data[type]).map(item => `${type}:${item.id}`))); } q('record-selection-action').value = ''; render(); }
function applyRecordAction(action) { if (action !== 'consume') return; const data = getData(), ids = selectedItems(data).filter(entry => entry.type === 'f3' && (entry.item.status || 'stock') !== 'consumed').map(entry => entry.item.id); if (!ids.length) { alert('Selecciona almenys una F3 que estigui en estoc.'); return; } data.f3 = data.f3.map(item => ids.includes(item.id) ? { ...item, status: 'consumed', consumedDate: item.consumedDate || today() } : item); ids.forEach(id => selectedRecords.delete(`f3:${id}`)); saveData(data); render(); }

q('f1-form').onsubmit = event => { event.preventDefault(); const data = getData(), item = { id: editingF1 || crypto.randomUUID(), date:q('f1-date').value, lot:q('f1-lot').value.trim(), liters:q('f1-liters').value, temperature:q('f1-temperature').value, ph:q('f1-ph').value, days:q('f1-days').value, notes:q('f1-notes').value.trim(), photos:pendingF1Photos }; data.f1 = editingF1 ? data.f1.map(x => x.id === editingF1 ? item : x) : [item, ...data.f1]; saveData(data); localStorage.removeItem(draftKey); resetF1(); render(); };
q('f2-form').onsubmit = event => { event.preventDefault(); const data = getData(), item = { id: editingF2 || crypto.randomUUID(), f1Id:q('f2-f1-id').value, name:q('f2-name').value.trim(), date:q('f2-date').value, lot:q('f2-lot').value.trim(), liters:q('f2-liters').value, components:formComponents(), days:q('f2-days').value, ingredients:q('f2-ingredients').value.trim(), notes:q('f2-notes').value.trim(), photos:pendingPhotos }; data.f2 = editingF2 ? data.f2.map(x => x.id === editingF2 ? item : x) : [item, ...data.f2]; saveData(data); localStorage.removeItem(draftKey); resetF2(); render(); };
q('f3-form').onsubmit = event => { event.preventDefault(); const data = getData(), status = q('f3-status').value, item = { id:editingF3 || crypto.randomUUID(), f2Id:q('f3-f2-id').value, date:q('f3-date').value, liters:q('f3-liters').value, bottles:q('f3-bottles').value, lot:q('f3-lot').value.trim(), storageTemperature:q('f3-storage-temperature').value, status, bestBefore:q('f3-best-before').value, consumedDate:status === 'consumed' ? q('f3-consumed-date').value || today() : '', notes:q('f3-notes').value.trim(), photos:pendingF3Photos }; data.f3 = editingF3 ? data.f3.map(x => x.id === editingF3 ? item : x) : [item, ...data.f3]; saveData(data); localStorage.removeItem(draftKey); resetF3(); render(); };
q('record-action').onchange = () => { const action = q('record-action').value; q('record-action').value = ''; applyRecordAction(action); };

var activeProductionPhase = 'f1';
var activeRegistryPanel = 'f1';
function setProductionPhase(phase) { activeProductionPhase = phase; document.querySelectorAll('[data-phase-panel]').forEach(panel => panel.hidden = panel.dataset.phasePanel !== phase); document.querySelectorAll('[data-phase-button]').forEach(button => button.classList.toggle('is-active', button.dataset.phaseButton === phase)); }
function renderRegistrySummary(data) { const stock = data.f3.filter(item => (item.status || 'stock') !== 'consumed').length, consumed = data.f3.filter(item => item.status === 'consumed').length; q('summary-f1').textContent = data.f1.length; q('summary-f2').textContent = data.f2.length; q('summary-stock').textContent = stock; q('summary-consumed').textContent = consumed; }
function setRegistryPanel(panel) { activeRegistryPanel = panel; document.querySelectorAll('[data-registry-panel]').forEach(section => section.hidden = section.dataset.registryPanel !== panel); document.querySelectorAll('[data-registry-button]').forEach(button => button.classList.toggle('is-active', button.dataset.registryButton === panel)); }
function setViewUpdated(view) { document.querySelectorAll('[data-view]').forEach(panel => panel.hidden = panel.dataset.view !== view || (panel.id === 'comparison-panel' && !q('comparison-table').innerHTML)); const productionTabs = document.querySelector('.production-subtabs'); if (productionTabs) productionTabs.hidden = view !== 'production'; document.querySelectorAll('[data-view-button]').forEach(button => { const active = button.dataset.viewButton === view; button.classList.toggle('is-active',active); button.setAttribute('aria-selected',String(active)); }); if (view === 'production') setProductionPhase(activeProductionPhase || 'f1'); if (view === 'registry') setRegistryPanel(activeRegistryPanel || 'f1'); }
function editF3Updated(item) { editingF3 = item.id; renderSelectors(getData()); [['f3-f2-id',item.f2Id],['f3-date',item.date],['f3-liters',item.liters],['f3-bottles',item.bottles],['f3-lot',item.lot],['f3-storage-temperature',item.storageTemperature],['f3-status',item.status || 'stock'],['f3-best-before',item.bestBefore],['f3-consumed-date',item.consumedDate],['f3-notes',item.notes]].forEach(([id,value]) => q(id).value = value || ''); pendingF3Photos = [...(item.photos || [])]; q('f3-title').textContent = 'Edita la conservació F3'; q('save-f3').textContent = 'Desa els canvis'; showF3Photos(); setView('production'); setProductionPhase('f3'); q('f3-form').scrollIntoView({ behavior: 'smooth' }); }
document.querySelectorAll('[data-phase-button]').forEach(button => button.onclick = () => setProductionPhase(button.dataset.phaseButton));
document.querySelectorAll('[data-registry-button]').forEach(button => button.onclick = () => setRegistryPanel(button.dataset.registryButton));

